services:
  # run jupyter notebook inside jupyter 
  jupyter-notebook:
    image: 123456789nelli/maternal_health_classification:latest
    ports:
      - "8888:8888"
    volumes:
      - .:/home/jovyan
    deploy:
      resources:
        limits:
          memory: 5G
    platform: linux/amd64