# Install the conda environment with the following command:
# conda env create -f environment.yaml
# Once you install it, you should be able to see it in your Jupyter Lab.
# If not, check the documentation here: https://ipython.readthedocs.io/en/stable/install/kernel_install.html
name: "522"
channels:
  - conda-forge
  - defaults
dependencies:
  - altair=5.1.2
  - ipykernel=6.26.0
  - pandas=2.1.2
  - python=3.11.6
  - scikit-learn=1.3.2
  - vegafusion=1.4.3
  - vegafusion-jupyter=1.4.3
  - vegafusion-python-embed=1.4.3
  - vl-convert-python=1.0.1
  - requests=2.31.0
  - notebook=6.5.4
  - jupyter_contrib_nbextensions=0.7.0
  - nb_conda_kernels=2.5.1
  - jupyterlab=4.3.1
  - matplotlib=3.9.2
  - pandera=0.20.4
  - pip
  - pip:
    - altair_viewer==0.4.0
    - deepchecks==0.18.1
